-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Versione server:              10.4.32-MariaDB - mariadb.org binary distribution
-- S.O. server:                  Win64
-- HeidiSQL Versione:            12.7.0.6850
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- Dump della struttura di tabella americandream.owned_vehicles
CREATE TABLE IF NOT EXISTS `owned_vehicles` (
  `owner` varchar(47) DEFAULT NULL,
  `plate` varchar(12) NOT NULL,
  `veicolo` longtext DEFAULT NULL,
  `modello` varchar(50) DEFAULT NULL,
  `acquisto` varchar(50) DEFAULT NULL,
  `garage` int(4) NOT NULL DEFAULT 1,
  `garageCasa` longtext DEFAULT NULL,
  `vehicle` longtext DEFAULT NULL,
  `fuori` int(11) DEFAULT 0,
  `sequestrato` int(11) DEFAULT 0,
  `glovebox` longtext DEFAULT NULL,
  `trunk` longtext DEFAULT NULL,
  `noleggio` longtext DEFAULT NULL,
  `type` varchar(50) DEFAULT 'veicolo',
  `carseller` int(11) DEFAULT 0,
  PRIMARY KEY (`plate`),
  KEY `idx_plate` (`plate`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Dump dei dati della tabella americandream.owned_vehicles: ~5 rows (circa)
INSERT INTO `owned_vehicles` (`owner`, `plate`, `veicolo`, `modello`, `acquisto`, `garage`, `garageCasa`, `vehicle`, `fuori`, `sequestrato`, `glovebox`, `trunk`, `noleggio`, `type`, `carseller`) VALUES
	('cri', 'CRI737MI', 'compasscri', 'Jeep Compass', NULL, 1, NULL, '{"modAerials":-1,"neonEnabled":[false,false,false,false],"modHydrolic":-1,"modEngine":-1,"bodyHealth":1000.0,"extras":{"7":false,"4":false,"3":false,"2":false,"1":false,"8":false},"modShifterLeavers":-1,"modVanityPlate":-1,"modFrontWheels":-1,"modTurbo":false,"modArchCover":-1,"fuelLevel":71.7,"modTank":-1,"modPlateHolder":-1,"tyreBurst":{"4":false,"1":false,"5":false,"0":false},"modAirFilter":-1,"modWindows":-1,"modTrimB":-1,"modSeats":-1,"wheels":3,"modOrnaments":-1,"modXenon":false,"tyresCanBurst":1,"modStruts":-1,"modSteeringWheel":-1,"modEngineBlock":-1,"model":-62834841,"modFrontBumper":-1,"pearlescentColor":4,"modSmokeEnabled":false,"modLightbar":-1,"modRoof":-1,"windowTint":-1,"modSpeakers":-1,"color2":112,"modRightFender":-1,"dirtLevel":1.1,"modDial":-1,"color1":112,"doorsBroken":{"6":false,"5":false,"4":false,"3":false,"2":false,"1":false,"0":false},"dashboardColor":0,"windowsBroken":{"7":false,"6":false,"5":false,"4":false,"3":false,"2":false,"1":false,"0":false},"tankHealth":1000.0,"modDoorSpeaker":-1,"modRoofLivery":-1,"modHood":-1,"tyreSmokeColor":[255,255,255],"xenonColor":255,"modTrimA":-1,"modCustomFrontWheels":false,"modSideSkirt":-1,"modAPlate":-1,"modFrame":-1,"modCustomBackWheels":false,"modGrille":-1,"engineHealth":1000.0,"plateIndex":4,"neonColor":[255,0,255],"modExhaust":-1,"plate":"CRI737MI","interiorColor":0,"modTransmission":-1,"modRearBumper":-1,"modSuspension":-1,"modHorns":-1,"modFender":-1,"modDashboard":-1,"wheelColor":4,"modArmor":-1,"modBrakes":-1,"modSpoilers":-1,"modBackWheels":-1,"modTrunk":-1,"modLivery":-1}', 0, 0, '[{"name":"legbrace","count":3,"slot":1},{"name":"neckbrace","count":2,"slot":2}]', NULL, NULL, 'veicolo', 0),
	('aci', 'DI381JX', 'flatbed', 'Mercedes Pianale', NULL, 1, NULL, '{"tankHealth":1000.0,"modFrame":-1,"modHood":-1,"plate":"DI381JX","modStruts":-1,"tyreSmokeColor":[255,255,255],"modRoofLivery":-1,"modPlateHolder":-1,"modTank":-1,"modCustomFrontWheels":false,"modSpoilers":-1,"modArmor":-1,"dirtLevel":0.3,"fuelLevel":97.8,"extras":{"9":false,"3":false,"4":false,"1":1,"2":false,"7":false,"12":false},"neonEnabled":[false,false,false,false],"modSeats":-1,"color1":45,"modSteeringWheel":-1,"modFender":-1,"wheelColor":156,"modHydrolic":-1,"modRoof":-1,"modSmokeEnabled":false,"modGrille":-1,"neonColor":[255,0,255],"modShifterLeavers":-1,"modSideSkirt":-1,"modExhaust":-1,"modOrnaments":-1,"modAerials":-1,"modHorns":-1,"interiorColor":0,"tyreBurst":{"5":false,"1":false,"4":false,"0":false},"modTurbo":false,"modAPlate":-1,"plateIndex":3,"modLivery":-1,"modTrimB":-1,"model":1353720154,"modXenon":false,"doorsBroken":{"1":false,"2":false,"0":false},"modDial":-1,"tyresCanBurst":1,"modWindows":-1,"dashboardColor":0,"modFrontWheels":-1,"modAirFilter":-1,"modLightbar":-1,"modEngineBlock":-1,"modArchCover":-1,"modBrakes":-1,"xenonColor":255,"windowTint":-1,"modCustomBackWheels":false,"modRightFender":-1,"modSpeakers":-1,"bodyHealth":1000.0,"modSuspension":-1,"modFrontBumper":-1,"modVanityPlate":-1,"modTrunk":-1,"modEngine":-1,"modBackWheels":-1,"color2":40,"engineHealth":1000.0,"modRearBumper":-1,"wheels":0,"pearlescentColor":35,"modTrimA":-1,"modDashboard":-1,"modDoorSpeaker":-1,"modTransmission":-1,"windowsBroken":{"5":true,"6":false,"3":true,"4":true,"1":false,"2":true,"7":true,"0":false}}', 0, 0, '[{"metadata":{"durability":100,"ammo":100,"components":[]},"count":1,"slot":11,"name":"WEAPON_PETROLCAN"}]', NULL, NULL, 'veicolo', 0),
	('esercito', 'EI72DH', 'renegadeei', 'Jeep Renegade', NULL, 1, NULL, '{"modTank":-1,"modAerials":-1,"modBrakes":-1,"modXenon":false,"tyreSmokeColor":[255,255,255],"modEngine":-1,"modTrunk":-1,"modFrame":-1,"modCustomFrontWheels":false,"model":173174354,"plate":"EI72DH","modOrnaments":-1,"modSideSkirt":-1,"doorsBroken":{"3":false,"4":false,"1":false,"2":false,"0":false},"interiorColor":0,"tankHealth":999.6,"windowsBroken":{"5":false,"6":false,"3":false,"4":false,"1":false,"2":false,"7":false,"0":false},"windowTint":-1,"modRoof":-1,"modDial":-1,"modSmokeEnabled":false,"modTrimB":-1,"modCustomBackWheels":false,"modSteeringWheel":-1,"extras":[],"modExhaust":-1,"bodyHealth":996.2,"modHydrolic":-1,"modHorns":-1,"modFrontWheels":-1,"modPlateHolder":-1,"modDoorSpeaker":-1,"plateIndex":0,"dirtLevel":15.0,"modLivery":0,"engineHealth":969.2,"modLightbar":-1,"modEngineBlock":-1,"modShifterLeavers":-1,"modBackWheels":-1,"modStruts":-1,"dashboardColor":0,"modWindows":-1,"modSeats":-1,"fuelLevel":64.6,"modDashboard":-1,"color2":0,"modSuspension":-1,"wheelColor":0,"modRightFender":-1,"modFender":-1,"neonColor":[255,0,255],"color1":4,"modHood":-1,"modFrontBumper":-1,"modSpoilers":-1,"wheels":0,"modVanityPlate":-1,"modAirFilter":-1,"xenonColor":255,"pearlescentColor":122,"modArchCover":-1,"modSpeakers":-1,"modArmor":-1,"modRearBumper":-1,"neonEnabled":[false,false,false,false],"tyreBurst":{"1":false,"4":false,"5":false,"0":false},"modTrimA":-1,"modRoofLivery":-1,"modAPlate":-1,"modGrille":-1,"modTransmission":-1,"modTurbo":false,"tyresCanBurst":1}', 1, 0, NULL, NULL, NULL, 'veicolo', 0),
	('vvf', 'VF857MI', 'tzvvfaps290', 'Volvo 290 APS', NULL, 1, NULL, '{"tyresCanBurst":1,"modRoof":-1,"modRearBumper":-1,"modTank":-1,"modSpeakers":-1,"modTrimB":-1,"modSideSkirt":-1,"modAPlate":-1,"modDashboard":-1,"modOrnaments":-1,"modEngine":-1,"modRoofLivery":-1,"model":910374753,"modArchCover":-1,"extras":{"7":false,"9":false,"8":false,"3":false,"2":false,"1":false,"4":false},"modBackWheels":-1,"modCustomFrontWheels":false,"bodyHealth":1000.0,"xenonColor":255,"plate":"VF857MI","modLightbar":-1,"modSmokeEnabled":false,"modTransmission":-1,"pearlescentColor":156,"interiorColor":0,"modCustomBackWheels":false,"modFrontBumper":-1,"dirtLevel":0.5,"modTurbo":false,"modHydrolic":-1,"modLivery":-1,"neonColor":[255,0,255],"modWindows":-1,"tankHealth":1000.0,"modSuspension":-1,"neonEnabled":[false,false,false,false],"modXenon":false,"wheelColor":156,"modRightFender":-1,"modEngineBlock":-1,"color2":134,"modArmor":-1,"modVanityPlate":-1,"engineHealth":1000.0,"modExhaust":-1,"modShifterLeavers":-1,"modHorns":-1,"plateIndex":4,"modFender":-1,"modFrame":-1,"modAirFilter":-1,"windowsBroken":{"7":true,"6":false,"1":false,"0":false,"3":false,"2":false,"5":true,"4":true},"fuelLevel":92.7,"dashboardColor":0,"modStruts":-1,"modHood":-1,"modAerials":-1,"modSpoilers":-1,"modPlateHolder":-1,"modTrunk":-1,"modSteeringWheel":-1,"modFrontWheels":-1,"tyreSmokeColor":[255,255,255],"modDoorSpeaker":-1,"color1":134,"doorsBroken":{"7":false,"6":false,"1":false,"0":false,"3":false,"2":false,"5":false,"4":false},"modGrille":-1,"modBrakes":-1,"windowTint":-1,"modSeats":-1,"tyreBurst":{"4":false,"5":false,"1":false,"0":false},"modTrimA":-1,"modDial":-1,"wheels":0}', 0, 0, NULL, NULL, NULL, 'veicolo', 0),
	('dream1:343d2a215fb139191e646af1f9195a454b231d12', 'XS495OO', 'alpinab7', 'Alpina B7', '15/01/2025', 1, NULL, '{"modDashboard":-1,"modTank":-1,"tyreSmokeColor":[255,255,255],"windowsBroken":{"1":false,"0":false,"3":false,"2":false,"5":true,"4":true,"7":false,"6":false},"modTrimB":-1,"modGrille":-1,"modRoofLivery":-1,"modCustomFrontWheels":false,"modRearBumper":-1,"model":-2035069692,"modBackWheels":-1,"modAirFilter":-1,"modSideSkirt":-1,"dirtLevel":3.0,"modLivery":-1,"tankHealth":1000.0,"modSmokeEnabled":false,"modAPlate":-1,"modXenon":false,"modCustomBackWheels":false,"modHorns":-1,"xenonColor":255,"engineHealth":1000.0,"modDial":-1,"pearlescentColor":67,"modArchCover":-1,"modRightFender":-1,"neonEnabled":[false,false,false,false],"plate":"XS495OO","modVanityPlate":-1,"modArmor":-1,"modHood":-1,"modFrontWheels":-1,"modFender":-1,"modOrnaments":-1,"modHydrolic":-1,"windowTint":-1,"modExhaust":-1,"modLightbar":-1,"modPlateHolder":-1,"plateIndex":3,"interiorColor":0,"tyreBurst":{"5":false,"4":false,"1":false,"0":false},"modEngine":-1,"modSuspension":-1,"modFrame":-1,"modDoorSpeaker":-1,"modAerials":-1,"modWindows":-1,"dashboardColor":0,"tyresCanBurst":1,"modTransmission":-1,"modSpeakers":-1,"modBrakes":-1,"modStruts":-1,"modTurbo":false,"modTrimA":-1,"wheelColor":67,"modTrunk":-1,"extras":{"1":false,"7":false},"modSpoilers":-1,"color1":67,"modShifterLeavers":-1,"neonColor":[255,0,255],"modFrontBumper":-1,"modSteeringWheel":-1,"color2":67,"modSeats":-1,"modRoof":-1,"doorsBroken":{"1":false,"0":false,"3":false,"2":false,"5":false,"4":false,"6":false},"wheels":0,"bodyHealth":1000.0,"fuelLevel":65.0,"modEngineBlock":-1}', 0, 0, NULL, NULL, NULL, 'veicolo', 0);

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
